blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name="list"),
    path('create/', never_cache(ArticleCreateView.as_view()), name="create"),
    path('view/<slug:slug>', ArticleDetailView.as_view(), name="view"),
    path('update/<slug:slug>', never_cache(ArticleUpdateView.as_view()), name="update"),
    path('delete/<slug:slug>', never_cache(ArticleDeleteView.as_view()), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name="заголовок")
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name="slug")
    content = models.TextField(verbose_name="содержимое")
    image = models.ImageField(upload_to='article/', verbose_name="превью")
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    is_published = models.BooleanField(default=True, verbose_name="признак публикации")
    view_count = models.IntegerField(default=0, verbose_name="количество просмотров")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              **NULLABLE, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.title} {self.create_at} {self.is_published}"

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

blog/forms.py
from django import forms
from blog.models import Article
from catalog.forms import StyleFormMixin


class ArticleForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'image', 'is_published',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.forms import ArticleForm
from blog.models import Article


class ArticleListView(ListView):
    model = Article
    extra_context = {
        'title': 'Статьи'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'blog.view_article'
    model = Article
    extra_context = {
        'title': 'Статьи'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'blog.add_article'
    model = Article
    form_class = ArticleForm
    extra_context = {
        'title': 'Добавление статьи'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.owner = self.request.user
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.slug])


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'blog.change_article'
    model = Article
    form_class = ArticleForm
    extra_context = {
        'title': 'Редактирование статьи'
    }

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.slug])


class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'blog.delete_article'
    model = Article
    extra_context = {
        'title': 'Удаление статьи'
    }

    success_url = reverse_lazy("blog:list")

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-3 card shadow-lg">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <p>Вы действительно хотет удалить статью:<br><i>{{ object.title }}</i></p>
                <img src="{{ object.image | media_url }}" style="width:100%">
                <div class="row">
                    <button type="submit" class="btn btn-danger mt-2">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning mt-1">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <b class="pr_inf">{{ object.title }}</b>
                </div>
                <div class="card-body">
                    <img src="{{ object.image | media_url }}" style="width:100%;height:30em;">
                    <p class="mt-4">{{ object.content }}...</p>
                    <b>Дата публикации:</b> {{ object.create_at }}<br>
                    <b>Количество просмотров:</b> {{ object.view_count }}<br>
                    <p><b>Автор:</b> {{ object.owner|default:'неизвестен' }}</p>
                    {% if perms.blog.delete_article and perms.blog.change_article or user == object.owner %}
                    <a href="{% url 'blog:update' object.slug %}" class="btn btn-warning">Редактировать</a>
                    <a href="{% url 'blog:delete' object.slug %}" class="btn btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow shadow-lg">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center">Статья</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-success form-control" type="submit">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Добавить
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    {% if perms.blog.add_article %}
    <a href="{% url 'blog:create' %}" class="btn btn-outline-success btn-lg btn-block mb-3">Добавить статью</a>
    {% endif %}
    {% for object in object_list %}
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <b class="pr_inf">{{ object.title }}</b>
                </div>
                <div class="card-body">
                    <img src="{{ object.image | media_url }}" style="width:100%;height:30em;">
                    <p class="mt-4">{{ object.content | slice:200 }}...</p>
                    <p><b>Количество просмотров:</b> {{ object.view_count }}</p>
                    <a href="{% url 'blog:view' object.slug %}" class="btn btn-success">Читать</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}