blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name="list"),
    path('create/', never_cache(ArticleCreateView.as_view()), name="create"),
    path('view/<slug:slug>', ArticleDetailView.as_view(), name="view"),
    path('update/<slug:slug>', never_cache(ArticleUpdateView.as_view()), name="update"),
    path('delete/<slug:slug>', never_cache(ArticleDeleteView.as_view()), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserLogoutView, email_verification, UserPasswordResetView, \
    UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('confirm-email/<str:token>/', email_verification, name='confirm-email'),
    path('recovery/', UserPasswordResetView.as_view(), name='recovery'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from blog.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name="Email")
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name="Телефон")
    country = models.CharField(max_length=100, **NULLABLE, verbose_name="Страна")
    avatar = models.ImageField(upload_to='users/avatars/', **NULLABLE, verbose_name="Аватар")
    token = models.CharField(max_length=100, **NULLABLE, verbose_name='Токен')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, UserChangeForm
from catalog.forms import StyleFormMixin
from users.models import User


class RegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class LoginForm(StyleFormMixin, AuthenticationForm):
    pass


class RecoveryForm(StyleFormMixin, PasswordResetForm):
    pass


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'country', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from config.settings import EMAIL_HOST_USER
from users.forms import RegisterForm, LoginForm, RecoveryForm, UserForm
from users.models import User
from users.services import make_random_password


class UserRegisterView(CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(12)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/confirm-email/{token}/'
        try:
            send_mail(
                subject="Подтверждение регистрации",
                message=f"Здравствуйте!\n"
                        f"Для подтверждения регистрации на сайте ({host}) перейдите по ссылки {url}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
        except Exception:
            print(f"Ошибка при отправке письма верификации")
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    pass


class UserPasswordResetView(PasswordResetView):
    form_class = RecoveryForm
    template_name = 'users/recovery_form.html'

    def form_valid(self, form):
        if self.request.method == 'POST':
            user_email = self.request.POST['email']
            user = User.objects.filter(email=user_email).first()
            if user:
                password = make_random_password()
                user.set_password(password)
                user.save()
                host = self.request.get_host()
                try:
                    send_mail(
                        subject="Восстановление пароля",
                        message=f"Здравствуйте! "
                                f"Ваш пароль для доступа на сайт {host} изменен:\n"
                                f"Данные для входа:\n"
                                f"Email: {user_email}\n"
                                f"Пароль: {password}",
                        from_email=EMAIL_HOST_USER,
                        recipient_list=[user.email]
                    )
                except Exception:
                    print(f"Ошибка при отправке пароля юзеру: ({user=}), на email: {user_email}")
            return HttpResponseRedirect(reverse('users:login'))
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">Авторизация</h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success form-control">
                        Войти
                    </button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:recovery' %}" class="btn btn-danger form-control">Восстановление пароля</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/recovery_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">
                    Форма восстановления
                </h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="w-100 btn btn-block btn-outline-success">
                        Восстановить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">
                    {% if user.is_authenticated %}
                    Профиль
                    {% else %}
                    Регистрация
                    {% endif %}
                </h4>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="w-100 btn btn-block btn-outline-success">
                        {% if user.is_authenticated %}
                        Сохранить
                        {% else %}
                        Зарегистрироваться
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}