blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name="list"),
    path('create/', never_cache(ArticleCreateView.as_view()), name="create"),
    path('view/<slug:slug>', ArticleDetailView.as_view(), name="view"),
    path('update/<slug:slug>', never_cache(ArticleUpdateView.as_view()), name="update"),
    path('delete/<slug:slug>', never_cache(ArticleDeleteView.as_view()), name="delete"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, FeedbackCreateView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, CategoryListView, CategoryDetailView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name="product_list"),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path('product/create/', never_cache(ProductCreateView.as_view()), name="product_create"),
    path('product/update/<int:pk>', never_cache(ProductUpdateView.as_view()), name="product_update"),
    path('product/delete/<int:pk>', never_cache(ProductDeleteView.as_view()), name="product_delete"),
    path('contacts/', FeedbackCreateView.as_view(), name="feedback_create"),
    path('category/', CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category_detail')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models

from blog.models import NULLABLE


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    image = models.ImageField(upload_to='product/', null=True, blank=True, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=0, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              **NULLABLE, verbose_name='Пользователь')
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')

    def __str__(self):
        return f"{self.name} {self.price} {self.category}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('can_change_description', 'Can change description'),
            ('can_change_category', 'Can change category'),
            ('set_published_status', 'Can publish product')
        ]


class Contact(models.Model):
    """Контактная информация о компании"""
    name = models.CharField(max_length=100, verbose_name="Название")
    address = models.CharField(max_length=250, verbose_name="Адрес")
    phone = models.CharField(max_length=20, verbose_name="Телефон")

    def __str__(self):
        return f"{self.name} | {self.address} | {self.phone}"

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class Feedback(models.Model):
    """Обратная связь"""
    name = models.CharField(max_length=45, verbose_name='Имя')
    phone = models.CharField(max_length=20, verbose_name='Номер')
    message = models.TextField(verbose_name='Сообщение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')

    def __str__(self):
        """Строковое представление сообщения feedback"""
        return f"{self.name} {self.phone}"

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='version', verbose_name="Продукт")
    version_number = models.CharField(max_length=15, verbose_name="Номер версии")
    version_name = models.CharField(max_length=100, verbose_name="Название версии")
    is_active = models.BooleanField(default=True, verbose_name="Признак версии")

    def __str__(self):
        return f"{self.version_name} ({self.version_number})"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version, Feedback

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fields_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = "form-check-input"
            else:
                field.widget.attrs['class'] = "form-control"


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'owner',)

    def clean_name(self):
        clean_data = self.cleaned_data.get('name')
        for word in FORBIDDEN_WORDS:
            if word in clean_data.lower():
                raise forms.ValidationError('Название продукта содержит запрещенное слово')
        return clean_data


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'description', 'is_published',)

    def clean_name(self):
        clean_data = self.cleaned_data.get('name')
        for word in FORBIDDEN_WORDS:
            if word in clean_data.lower():
                raise forms.ValidationError('Название продукта содержит запрещенное слово')
        return clean_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_version_name(self):
        clean_data = self.cleaned_data.get('version_name')
        for word in FORBIDDEN_WORDS:
            if word in clean_data.lower():
                raise forms.ValidationError('Название версии содержит запрещенное слово')
        return clean_data


class FeedbackForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('name', 'phone', 'message',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, FeedbackForm, ProductModeratorForm
from catalog.models import Product, Contact, Feedback, Version, Category
from catalog.services import get_products_from_cache, get_categories_from_cache


class ProductListView(ListView):
    model = Product
    extra_context = {
        "title": "Главная"
    }

    def get_queryset(self):
        return get_products_from_cache()


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    extra_context = {
        "title": "Товар"
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['version'] = self.object.version.filter(is_active=True).first()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        "title": "Добавление товара"
    }
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            self.object.owner = self.request.user
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        "title": "Редактирование товара"
    }

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ProductForm
        if user.has_perms(['catalog.can_change_category',
                           'catalog.can_change_description',
                           'catalog.set_published_status']):
            return ProductModeratorForm

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if (user != self.get_object().owner and not user.is_superuser and
                not user.groups.filter(name='moderator').exists()):
            raise PermissionDenied

        return super().dispatch(request, *args, **kwargs)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    extra_context = {
        "title": "Удаление товара"
    }
    success_url = reverse_lazy('catalog:product_list')

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if user != self.get_object().owner and not user.is_superuser:
            raise PermissionDenied

        return super().dispatch(request, *args, **kwargs)


class FeedbackCreateView(CreateView):
    model = Feedback
    form_class = FeedbackForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        context["contact"] = Contact.objects.get(pk=1)
        return context

    success_url = reverse_lazy("catalog:product_list")


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    extra_context = {
        "title": "Категории продуктов"
    }

    def get_queryset(self):
        return get_categories_from_cache()


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f"Категория - {self.object}"
        context_data['objects_list'] = Product.objects.filter(category=self.kwargs.get('pk'))
        return context_data

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - {{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% block menu %}
    {% include 'catalog/includes/inc_nav_menu.html' %}
{% endblock %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                TechShop
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row justify-content-center text-center">
        {% for object in objects_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"> {{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{object.image | media_url}}" style="width:50%"><br>
                    Цена: {{ object.price }} руб.<br>
                    Категория: {{ object.category }}<br>
                    Описание: {{ object.description | slice:100 }}
                </div>
                <a href="/product/{{object.pk}}" class="btn btn-success">Подробнее</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
        <div class="col mb-4 mt-4 text-center">
            <div class="card shadow-sm">
                <div class="card-header pr_inf">
                    {{ object.name }}
                </div>
                <div class="card-body">
                    {{ object.description }}
                </div>
                <div class="card-header">
                    <a class="btn btn-success" href="{% url 'catalog:category_detail' object.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Организация</td>
                            <td>{{ contact.name }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ contact.address }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Номер</td>
                            <td>{{ contact.phone }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/feedback_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Организация</td>
                            <td>{{ contact.name }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ contact.address }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Номер</td>
                            <td>{{ contact.phone }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-block btn-outline-primary form-control">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"> {{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{object.image | media_url}}" style="width:50%"><br>
                    Цена: {{ object.price }} руб.<br>
                    Категория: {{ object.category }}<br>
                    Описание: {{ object.description | slice:100 }}
                </div>
                <a href="/product/{{object.pk}}" class="btn btn-success">Подробнее</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card text-center">
                <div class="card-header">
                    {{ object.name }}
                </div>
                <div class="card-body">
                    <img src="{{object.image | media_url }}" style="width:50%"><br>
                    <b>Цена:</b> {{ object.price }} руб.<br>
                    <b>Категория:</b> {{ object.category }}<br>
                    <b>Описание:</b> {{ object.description }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-4 card shadow-lg">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <p>Вы действительно хотет удалить товар:<br><i>{{ object.name }}</i></p>
                <img src="/media/{{ object.image }}" style="width:100%">
                <div class="row">
                    <button type="submit" class="btn btn-danger mt-2">Подтвердить</button>
                    <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-warning mt-1">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row justify-content-center">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                {{ object.name }}
            </div>
            <div class="card-body">
                <p style="text-align:center"><img src="{{object.image | media_url }}" style="width:50%;"></p><br>
                <b>Цена:</b> {{ object.price }} руб.<br>
                <b>Категория:</b> {{ object.category }}<br>
                <b>Описание:</b> {{ object.description }}<br>
                <b>Добавил:</b> {{ object.owner|default:'аноним' }}<br>
                {% if version %}
                    <b>Номер версии:</b> {{ version.version_number }}<br>
                    <b>Название версии:</b> {{ version.version_name }}
                {% endif %}
                {% if user.is_authenticated %}
                <div class="col-12 mt-2">
                    {% if perms.catalog.can_change_category and perms.catalog.can_change_description and perms.catalog.set_published_status or user == object.owner %}
                        <a class="btn btn-warning" href="{% url 'catalog:product_update' object.pk %}">Редактировать</a>
                    {% endif %}
                    {% if perms.catalog.delete_product or user == object.owner %}
                        <a class="btn btn-danger" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center">Товар</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="w-100 btn btn-lg btn-block btn-outline-success">
                        {% if object %}
                            Изменить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        {% if perms.catalog.change_version or not object or object.owner %}
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center">Версия</h4>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    {% if user.is_authenticated %}
    <a href="{% url 'catalog:product_create' %}" class="btn btn-outline-success btn-lg btn-block mb-3">Добавить товар</a>
    {% endif %}
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"> {{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{object.image | media_url}}" style="width:50%"><br>
                    Цена: {{ object.price }} руб.<br>
                    Категория: {{ object.category }}<br>
                    Описание: {{ object.description | slice:100 }}
                </div>
                <a href="/product/{{object.pk}}" class="btn btn-success">Подробнее</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}